# Generated by Django 2.0.3 on 2018-11-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Court',
            new_name='SHG',
        ),
    ]
