# Generated by Django 2.0.3 on 2018-11-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181113_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerospace', models.DecimalField(blank=True, decimal_places=50, max_digits=55)),
                ('agribusiness', models.DecimalField(blank=True, decimal_places=50, max_digits=55)),
                ('agriculture', models.DecimalField(blank=True, decimal_places=50, max_digits=55)),
                ('air_transport', models.DecimalField(blank=True, decimal_places=50, max_digits=55)),
                ('airlines', models.DecimalField(blank=True, decimal_places=50, max_digits=55)),
                ('airport_harbour', models.DecimalField(blank=True, decimal_places=50, max_digits=55)),
                ('alcoholic_beverages', models.DecimalField(blank=True, decimal_places=50, max_digits=55)),
                ('amusement_parks', models.DecimalField(blank=True, decimal_places=50, max_digits=55)),
                ('auto_manufacure', models.DecimalField(blank=True, decimal_places=50, max_digits=55)),
                ('automobile', models.DecimalField(blank=True, decimal_places=50, max_digits=55)),
                ('automotive', models.DecimalField(blank=True, decimal_places=50, max_digits=55)),
            ],
        ),
    ]
