# Generated by Django 2.0.3 on 2018-11-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_villageindustry'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageindustry',
            name='vname',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
